import type { ECSPlugin } from '../';
export declare const defaultPlugins: ECSPlugin[];
export * from './audio';
export * from './input';
export * from './tween';
export * from './assets';
export * from './particle';
export * from './socket';
export * from './time';
export * from './transform';
