import { Vec2 } from '../../math/vec2';
export declare class PointerTracker {
    leftIsDown: boolean;
    leftIsUp: boolean;
    rightIsDown: boolean;
    rightIsUp: boolean;
    midIsDown: boolean;
    midIsUp: boolean;
    pos: Vec2;
    last: Vec2;
    offset: Vec2;
    private oldc;
    private oluc;
    private ordc;
    private oruc;
    private omdc;
    private omuc;
    private md;
    private mu;
    private mm;
    constructor();
    private ctm;
    private onMouseDown;
    private onMouseUp;
    private onMouseMove;
    onLeftDown(cb: () => void, thisArg?: any): void;
    onLeftUp(cb: () => void, thisArg?: any): void;
    onRightDown(cb: () => void, thisArg?: any): void;
    onRightUp(cb: () => void, thisArg?: any): void;
    onMidDown(cb: () => void, thisArg?: any): void;
    onMidUp(cb: () => void, thisArg?: any): void;
}
